#!/usr/bin/env node
import installed from "../elm-install.js";
if (installed) {
  process.stdout.write("stuff on stdout\n");
  process.stderr.write("stuff on stderr");
  process.stdout.write("second write to stdout");
  process.exit(2);
}
