#!/usr/bin/env node
import spawn from "cross-spawn";
import fs from "fs";
import path from "path";

const child = spawn("elm", process.argv.slice(2), {
  env: {
    ...process.env,
    PATH: process.env.PATH.split(path.delimiter)
      .filter((part) => !part.includes("bad-bin"))
      .join(path.delimiter),
  },
  stdio: "inherit",
});

child.on("exit", (exitCode) => {
  if (!process.argv.some((arg) => arg.includes("/dev/null"))) {
    const file = path.join(import.meta.dirname, "..", "..", "build", "Readonly.js");
    fs.chmodSync(file, "0444"); // readonly
  }
  process.exit(exitCode);
});
