#!/usr/bin/env node
import spawn from "cross-spawn";
import path from "path";
import fs from "fs";

const lockFile = path.join(import.meta.dirname, "..", "..", "lock");

const child = spawn("elm", process.argv.slice(2), {
  env: {
    ...process.env,
    PATH: process.env.PATH.split(path.delimiter)
      .filter((part) => !part.includes("bad-bin"))
      .join(path.delimiter),
  },
  stdio: "inherit",
});

child.on("exit", (exitCode) => {
  if (fs.readFileSync(lockFile, "utf8") === "Delay") {
    fs.writeFileSync(lockFile, "DelayAck");
    (function rec() {
      if (fs.readFileSync(lockFile, "utf8") === "Normal") {
        process.exit(exitCode);
      } else {
        setTimeout(rec, 10);
      }
    })();
  } else {
    process.exit(exitCode);
  }
});
