#!/usr/bin/env node
if (require("../elm-install")) {
  process.stderr.write(`This flag was given a bad value:

    --output=.js

I need a valid <output-file> value. For example:

    --output=elm.js
    --output=index.html
    --output=/dev/null
`);
  process.exit(1);
}
