#!/usr/bin/env node
const spawn = require("cross-spawn");
const fs = require("fs");
const path = require("path");

const child = spawn("elm", process.argv.slice(2), {
  env: {
    ...process.env,
    PATH: process.env.PATH.split(path.delimiter)
      .filter((part) => !part.includes("bad-bin"))
      .join(path.delimiter),
  },
  stdio: "inherit",
});

child.on("exit", (exitCode) => {
  if (!process.argv.some((arg) => arg.includes("/dev/null"))) {
    const file = path.join(__dirname, "..", "..", "build", "Removed.js");
    fs.unlinkSync(file);
  }
  process.exit(exitCode);
});
