#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
if (require("../elm-install")) {
  const file = path.join(__dirname, "..", "..", "build", "app.js");
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, "", {
    mode: "0444", // readonly
  });
  process.exit(0);
}
