remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
permalink: pretty

aux_links:
  "elm-watch on GitHub":
    - "https://github.com/lydell/elm-watch"

callouts:
  info:
    color: blue

  warning:
    color: red

