#!/usr/bin/env node
import spawn from "cross-spawn";
import fs from "fs";
import path from "path";

const argv = process.argv.slice(2);

const child = spawn("elm", argv, {
  env: {
    ...process.env,
    PATH: process.env.PATH.split(path.delimiter)
      .filter((part) => !part.includes("test-bin"))
      .join(path.delimiter),
  },
  stdio: "inherit",
});

child.on("exit", (exitCode) => {
  if (argv.some((arg) => arg.includes("2.js"))) {
    fs.writeFileSync(path.join(import.meta.dirname, "..", "lock"), "third-elm-done");
  }
  process.exit(exitCode);
});
