#!/usr/bin/env node
const spawn = require("cross-spawn");
const fs = require("fs");
const path = require("path");

const argv = process.argv.slice(2);

const child = spawn("elm", argv, {
  env: {
    ...process.env,
    PATH: process.env.PATH.split(path.delimiter)
      .filter((part) => !part.includes("test-bin"))
      .join(path.delimiter),
  },
  stdio: "inherit",
});

child.on("exit", (exitCode) => {
  if (argv.some((arg) => arg.includes("third"))) {
    fs.writeFileSync(path.join(__dirname, "..", "lock"), "third-elm-done");
  }
  process.exit(exitCode);
});
